<?xml version="1.0"?>
<package format="3">
  <name>mecharm_moveit_config</name>
  <version>0.1.0</version>
  <description>MoveIt 2 configuration for the mechArm 270 Pi adaptive gripper.</description>
  <maintainer email="xhr@example.com">xhr</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>mycobot_description</exec_depend>
  <exec_depend>moveit_configs_utils</exec_depend>
  <exec_depend>moveit_ros_move_group</exec_depend>
  <exec_depend>moveit_ros_visualization</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
